// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummerWebinarApp.Data;

#nullable disable

namespace SummerWebinarApp.Migrations
{
    [DbContext(typeof(SummerWebinarDbContext))]
    partial class SummerWebinarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STUDENTS_WEBINARS", b =>
                {
                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.Property<int>("WebinarsId")
                        .HasColumnType("int");

                    b.HasKey("StudentsId", "WebinarsId");

                    b.HasIndex("WebinarsId");

                    b.ToTable("STUDENTS_WEBINARS");
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Institution")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("INSTITUTION");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("STUDENTS", (string)null);
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Institution")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("INSTITUTION");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("TEACHERS", (string)null);
                });

            modelBuilder.Entity("SummerWebinarApp.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Firstname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FIRSTNAME");

                    b.Property<string>("Lastname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LASTNAME");

                    b.Property<string>("Password")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("PASSWORD");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_ROLE");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Lastname" }, "IX_LASTNAME");

                    b.HasIndex(new[] { "Email" }, "UQ_EMAIL")
                        .IsUnique()
                        .HasFilter("[EMAIL] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ_USERNAME")
                        .IsUnique()
                        .HasFilter("[USERNAME] IS NOT NULL");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Webinar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TEACHER_ID");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("WEBINARS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Description = "Java",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "JavaScript",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "MSSQL",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Python",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Angular",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 13,
                            Description = "Android",
                            TeacherId = 6
                        });
                });

            modelBuilder.Entity("STUDENTS_WEBINARS", b =>
                {
                    b.HasOne("SummerWebinarApp.Data.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SummerWebinarApp.Data.Webinar", null)
                        .WithMany()
                        .HasForeignKey("WebinarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Student", b =>
                {
                    b.HasOne("SummerWebinarApp.Data.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SummerWebinarApp.Data.Student", "UserId")
                        .HasConstraintName("FK_STUDENTS_USERS");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Teacher", b =>
                {
                    b.HasOne("SummerWebinarApp.Data.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("SummerWebinarApp.Data.Teacher", "UserId")
                        .HasConstraintName("FK_TEACHERS_USERS");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Webinar", b =>
                {
                    b.HasOne("SummerWebinarApp.Data.Teacher", "Teacher")
                        .WithMany("Webinars")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TEACHERS_WEBINARS");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SummerWebinarApp.Data.Teacher", b =>
                {
                    b.Navigation("Webinars");
                });

            modelBuilder.Entity("SummerWebinarApp.Data.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
